### ISSUE TITLE
Misspelled variable definition leads to errors during document export

### ISSUE THREAD

**Issue by Athemis** [LokeshN/ep_foot_note#1]
When trying to export a document (e.g. as PDF or ODT) with installed ep_foot_note, etherpad-lite crashes with the following error:

```
[2015-03-16 16:14:29.416] [ERROR] console - ReferenceError: ChangeSet is not defined
    at checkFootNoteInLine (/usr/share/webapps/etherpad-lite/node_modules/ep_foot_note/footNote.js:21:14)
    at Object.getLineHTMLForExport [as hook_fn] (/usr/share/webapps/etherpad-lite/node_modules/ep_foot_note/footNote.js:11:11)
    at normalizedhook (/usr/share/webapps/etherpad-lite/src/static/js/pluginfw/hooks.js:15:27)
    at hookCallWrapper (/usr/share/webapps/etherpad-lite/src/static/js/pluginfw/hooks.js:21:14)
    at /usr/share/webapps/etherpad-lite/src/static/js/pluginfw/hooks.js:76:14
    at Array.map (native)
    at Function._.map._.collect (/usr/share/webapps/etherpad-lite/src/node_modules/underscore/underscore.js:98:56)
    at Object.exports.callAll (/usr/share/webapps/etherpad-lite/src/static/js/pluginfw/hooks.js:75:24)
    at Object.exports.callAllStr (/usr/share/webapps/etherpad-lite/src/static/js/pluginfw/hooks.js:122:27)
    at getHTMLFromAtext (/usr/share/webapps/etherpad-lite/src/node/utils/ExportHtml.js:422:39)

```

The variable definition of "ChangeSet" is misspelled as "Changeset" in footNote.js

**Comment by LokeshN** [comment]
Fixed.
